on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cruizba/ubuntu-dind:latest
    steps:
      - uses: actions/checkout@v5

      - uses: psafonov7/cicd-toolkit/build-info@build-info-v1.0.0

      - uses: psafonov7/cicd-toolkit/docker@docker-v1.0.0
        with:
          build_number: ${{ env.BUILD_VERSION }}
          push: true
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_token: ${{ secrets.DOCKER_TOKEN }}
